---
title: "Welcome to the Lab"
page-navigation: false
listing:
  - id: events
    contents: "events/*qmd"
    type: default
    sort: "event-date desc"
    fields: [event-date, event-location, image, title, description]
    max-items: 3
  - id: news
    sort: "news-date desc"
    contents: "/"
    include:
      categories: [news]
    type: grid
    fields: [image, title, description]

---

<style>
.column {
  /* border: 1px solid #ddd; */
  padding: 1em;
  border-radius: 5px;
  /* 1. Make this column a flex container */
  display: flex;

  /* 2. Stack its children vertically */
  flex-direction: column;

  /* 3. Center the children horizontally */
  align-items: center;

  /* 4. Center the children vertically */
  justify-content: center; 

  /* 5. (Optional) Also center any text inside the children */
  text-align: center;
}

.column + .column {
  /* This adds the 1px solid grey vertical line */
  border-left: 1px solid #ddd;

  /* This adds some space between the line and the content 
  padding-left: 1em; */
}
</style>

The Wilson-Medimorec MIND Research Lab is a [collaborative research group](https://www.themindlabresearch.org/about.html) co-led by Dr Christopher Wilson and Dr Srdan Medimorec, who are based in the Department of Psychology at Teesside University. The lab’s work is organised into two primary research streams, each led by a Principal Investigator.

::: columns
::: {.column width="50%"}


**The Cognitive Neuroscience of Risk & Gambling Harms.**

[Learn more about gambling research here](research/gambling.qmd){.btn .btn-success}

:::
::: {.column width="50%"}



**Language, meta-cognition, implicit learning.** 

[Learn more about language and learning research here](research/langlearn.qmd){.btn .btn-success}

:::
:::


We use a range of methods, including functional near-infrared spectroscopy (fNIRS), eye-tracking, and virtual reality, to study these processes in both healthy and clinical populations.

::: {.callout}
## Joining the lab

If you are interested in joining the lab, the fist step is reading the [Lab Manual](info/lab_manual.html). This will give you an overview of the lab's research, methods, and culture.

:::

## Lab News

::: {#news}
:::

## Upcoming Events

The full lab meeting and event schedule can be found on the [Lab Schedule](info/lab_schedule.html) page.

::: {#events}
:::


